# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "clientname-extensions"
client_id = "6496264e311105e34800baeaf5b3296d"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "dawn-cli-experiments.myshopify.com"
